name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Build and publish
        uses: pypa/gh-action-pypi-publish@release/v1